---
- hosts: default

  vars_files:
    - "group_vars/all.yml"

  roles:
    - basic
    - systemupdate
    - dynmotd
    # BEGIN
    - CyVerse-Ansible.singularity
    - geerlingguy.java
    - geerlingguy.docker
    - andrewrothstein.miniconda
    - cvmfs
    # END
    - lock-root
    - cloudinit

  post_tasks:
    - lineinfile:
        path: /etc/environment
        line: 'export PATH="$PATH:/opt/miniconda/bin"'
