---
- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - patch
    - lsof
    - screen
    - ansible
    - vim
    - collectl
    - iotop
    - iftop
    - htop
    - atop
    - mosh
    - libcgroup-tools
    - autofs
    - bind-utils
    - strace
    - nfs-utils
    - "@development"
    - jq
    # Fonts
    - dejavu-fonts-common
    - dejavu-sans-fonts
    - fontconfig
    - fontconfig-devel
    - fontpackages-filesystem
    - ghostscript-fonts
    - libXfont
    - liberation-fonts-common
    - liberation-sans-fonts
    - libfontenc
    - urw-fonts
    - xorg-x11-font-utils
    - at

- name: Ensure services are enabled + started
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - atop
    - autofs
    - atd

- name: yum-autoupdate removal
  yum: name=yum-autoupdate state=absent

- name: Ensure firewalld stopped
  service:
    name: firewalld
    enabled: no
    state: stopped
